Herobrined:
  
  # Should we ignore players not in survival mode?
  survivalOnly: true
  
  # What actions aren't allowed? (Type /hb help ingame to view all actions)
  disallowedActions:
    - ExampleAction
    
  # What worlds are off limits to the plugin?
  disallowedWorlds:
    - ExampleWorld
    
  # What messages can he put on the signs he places?
  signMessages:
    - I'm watching.
    - Stop.
    - I'm here.
    - Never forget.
    - Brightness.