name: Herobrined
version: 6.0
main: com.kreckin.herobrined.Herobrined
description: I'll never stop.
author: steaks4uce
website: http://dev.bukkit.org/server-mods/herobrineunleashed/
commands:
  hb:
    description: Herobrined commands.
    usage: Use /hb