name: Herobrine
version: 7.1.5
main: com.kreckin.herobrine.Herobrine
description: I'll never stop.
author: nkrecklow
website: http://dev.bukkit.org/server-mods/herobrineunleashed/

permissions:
  herobrine.ignore:
    description: Ignore the player.
    
  herobrine.commands:
    description: Run commands.

commands:
  hb:
    description: Herobrine commands.
    usage: Please use /hb help!
  hbu:
    description: Herobrine commands.
    usage: Please use /hbu help!
